blog/urls.py
'''
blog urls
'''

from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^detail/(?P<article_id>\d+)/$', views.blog_detail, name="blog_detail"),
    url(r'^article_column/(?P<column_id>\d+)/$', views.blog_article_column, name='article_column'),
    url(r'^article_author/(?P<username>[-\w]+)/$', views.blog_article_author, name='article_author'),
    url(r'^article_post/$', views.article_post, name='article_post'),
    url(r'^article_del/$', views.article_delete, name='article_del'),
    url(r'^article_redit/(?P<article_id>\d+)/$', views.article_redit, name='article_redit'),
    url(r'^$', views.blog_title, name="blog_title"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

urlpatterns = [
    url(r'^robots\.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /admin\nDisallow: /login\nDisallow: /account\nDisallow: /wx', content_type='text/plain')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include("account.urls", namespace="account", app_name="account")),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    url(r'^wx/', include("wechat.urls", namespace="wechat", app_name="wechat")),
    url(r'^$', include("blog.urls", namespace="blog", app_name="blog")),
]

blog/models.py
# -*-coding:utf8-*-

from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from slugify import slugify
from django.contrib.auth.models import User


class ArticleColumn(models.Model):
    column = models.CharField(max_length=128, verbose_name='类目名')
    created = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ("id", "column")
        verbose_name = "博客栏目"
        verbose_name_plural = "博客栏目"

    def __str__(self):
        return self.column.encode("utf8")


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", verbose_name="作者")
    title = models.CharField(max_length=300, verbose_name="标题")
    slug = models.SlugField(max_length=100)
    article_column = models.ForeignKey(ArticleColumn, related_name="article_column", verbose_name="类目名")
    body = models.TextField(verbose_name="内容")
    created = models.DateField(auto_now_add=True, verbose_name="发布时间")
    updated = models.DateField(auto_now=True, verbose_name="更新时间")

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title.encode("utf8")

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("blog:article_column", args=[self.id, self.slug])


class ArticleComments(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments")
    name = models.CharField(max_length=90)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return "ArticleComments by {0} on {1}".format(self.name, self.article)

blog/forms.py
from django import forms
from .models import ArticlePost
from .models import ArticleComments

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

class CommentForm(forms.ModelForm):
    class Meta:
        model = ArticleComments
        fields = ("name", "email", "body", )

blog/back/views.py
# -*-coding:utf-8-*-

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.contrib.auth.models import User
from django.http import HttpResponse,HttpResponseRedirect
from django.db.models import Count
import traceback
import redisclient
import config
from markdown import markdown
from forms import ArticlePostForm, CommentForm
from models import ArticlePost, ArticleComments,ArticleColumn


# redis statistics
def blog_statistics(rediskey, field):
    client = redisclient.get_redis()
    return client.hincrby(rediskey, field)

def blog_sort_statistics(rediskey, score ,blogid):
    client = redisclient.get_redis()
    client.zadd(rediskey, blogid, score)

def get_blog_statistics(rediskey, field):
    client = redisclient.get_redis()
    return client.hget(rediskey, field)

def get_blog_sort_statistics(rediskey, size):
    client = redisclient.get_redis()
    return client.zrevrange(rediskey, 0, size)

# 首页视图数据
def blog_title(request):
    blogs = ArticlePost.objects.all().order_by("-created")
    paginator = Paginator(blogs, 8)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        blogs = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        blogs = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        blogs = current_page.object_list

    views = []
    if blogs and len(blogs) > 0:
        for blog in blogs:
            blog.column = ArticleColumn.objects.get(id=blog.article_column_id).column
            blog.body = markdown(blog.body)
            count = get_blog_statistics(config.BLOG_VIEWS, blog.id)
            if count == None:
                count = 0
            views.append({"id": blog.id, "views": count})

    mostids = get_blog_sort_statistics(config.BLOG_VIEWS_SORT, 10)
    mostidlist = [int(id) for id in mostids]
    mostblogs = list(ArticlePost.objects.filter(id__in=mostidlist))
    mostblogs.sort(key=lambda x: mostidlist.index(x.id))

    latest_articles = ArticlePost.objects.order_by("-created")[:5]
    most_comments = ArticlePost.objects.annotate(total_comments=Count('comments')).order_by("-total_comments")[:5]
    columns = ArticleColumn.objects.all().order_by("created")
    return render(request, "blog/titles.html", {"blogs": blogs,
                                                "most_views": mostblogs,
                                                "latest_articles": latest_articles,
                                                "most_comments": most_comments,
                                                "columns": columns,
                                                "views": views,
                                                "page": current_page})

# 博文详情页视图
def blog_detail(request, article_id):
    article = get_object_or_404(ArticlePost, id=article_id)
    article.column = ArticleColumn.objects.get(id=article.article_column_id).column
    columns = ArticleColumn.objects.all().order_by("created")

    count = blog_statistics(config.BLOG_VIEWS, article_id)
    blog_sort_statistics(config.BLOG_VIEWS_SORT, count, article_id)

    mostids = get_blog_sort_statistics(config.BLOG_VIEWS_SORT, 5)
    mostidlist = [int(id) for id in mostids]
    mostblogs = list(ArticlePost.objects.filter(id__in=mostidlist))
    mostblogs.sort(key=lambda x: mostidlist.index(x.id))

    latest_articles = ArticlePost.objects.order_by("-created")[:5]
    most_comments = ArticlePost.objects.annotate(total_comments=Count('comments')).order_by("-total_comments")[:5]

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            comment_form.save()

        #重定向到页面中的评论栏
        return HttpResponseRedirect(request.path+"#article_comment")
    else:
        comment_form = CommentForm()

    return render(request, "blog/content.html", {"article": article,
                                                 "columns": columns,
                                                 "views": count,
                                                 "most_views": mostblogs,
                                                 "latest_articles": latest_articles,
                                                 "most_comments": most_comments,
                                                 "comment_form": comment_form})


# 头部栏目查询视图
def blog_article_column(request, column_id):
    articles = ArticlePost.objects.filter(article_column=column_id).order_by("-created")
    paginator = Paginator(articles, 8)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list

    views = []
    if articles and len(articles) > 0:
        for blog in articles:
            blog.column = ArticleColumn.objects.get(id=blog.article_column_id).column
            blog.body = markdown(blog.body)
            count = get_blog_statistics(config.BLOG_VIEWS, blog.id)
            if count == None:
                count = 0
            views.append({"id": blog.id, "views": count})

    mostids = get_blog_sort_statistics(config.BLOG_VIEWS_SORT, 5)
    mostidlist = [int(id) for id in mostids]
    mostblogs = list(ArticlePost.objects.filter(id__in=mostidlist))
    mostblogs.sort(key=lambda x: mostidlist.index(x.id))

    latest_articles = ArticlePost.objects.order_by("-created")[:5]
    most_comments = ArticlePost.objects.annotate(total_comments=Count('comments')).order_by("-total_comments")[:5]
    columns = ArticleColumn.objects.all().order_by("created")

    retObj = {}
    if articles == None:
        retObj = {"columns": columns,
                  "most_views": mostblogs}
    else:
        retObj = {"blogs": articles,
                  "most_views": mostblogs,
                  "latest_articles": latest_articles,
                  "most_comments": most_comments,
                  "columns": columns,
                  "views": views,
                  "page": current_page}

    return render(request, "blog/titles.html", retObj)

# 某用户下的所有文章视图
def blog_article_author(request, username=None):
    articles = None
    if username:
        user = User.objects.get(username=username)
        articles = ArticlePost.objects.filter(author=user).order_by("-created")
    else:
        articles = ArticlePost.objects.all().order_by("-created")

    paginator = Paginator(articles, 8)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list

    views = []
    if articles and len(articles) > 0:
        for blog in articles:
            blog.column = ArticleColumn.objects.get(id=blog.article_column_id).column
            blog.body = markdown(blog.body)
            count = get_blog_statistics(config.BLOG_VIEWS, blog.id)
            if count == None:
                count = 0
            views.append({"id": blog.id, "views": count})

    mostids = get_blog_sort_statistics(config.BLOG_VIEWS_SORT, 5)
    mostidlist = [int(id) for id in mostids]
    mostblogs = list(ArticlePost.objects.filter(id__in=mostidlist))
    mostblogs.sort(key=lambda x: mostidlist.index(x.id))

    columns = ArticleColumn.objects.all().order_by("created")

    retObj = {}
    if articles == None:
        retObj = {"columns": columns}
    else:
        retObj = {"blogs": articles,
                  "most_views": mostblogs,
                  "columns": columns,
                  "views":views,
                  "page": current_page}

    return render(request, "blog/titles.html", retObj)

#博文新增
@login_required
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_aritcle = article_post_form.save(commit=False)
                new_aritcle.author = request.user
                new_aritcle.article_column = ArticleColumn.objects.get(id=request.POST["column_id"])
                new_aritcle.save()
                return HttpResponse("1")
            except:
                traceback.print_exc()
                return HttpResponse("2")

        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = ArticleColumn.objects.all().order_by("created")

        return render(request, "blog/article_post.html", {"article_post_form": article_post_form, "article_columns":article_columns})

#博文删除
@login_required
@require_POST
@csrf_exempt
def article_delete(request):
    try:
        article_id = request.POST["article_id"]
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

#博文编辑
@login_required
@csrf_exempt
def article_redit(request, article_id):
    if request.method == "GET":
        article_columns = ArticleColumn.objects.all().order_by("created")
        article = ArticlePost.objects.get(id=article_id)

templates/blog/article_comment.html
{% load staticfiles %}

<div id="article_comment">
    <div style="margin-top:5px" class="well">
        <h4 style="margin-top:0px">
            <span class="glyphicon glyphicon-bullhorn"></span>本文有{{ article.comments.count }}评论
        </h4>
        {% for comment in article.comments.all %}
        <div style="margin-top:20px" class="well well-sm">
            <span class="glyphicon glyphicon-user">
                <span class="label label-default">{{ comment.name }}</span>
                <span class="label label-info">#{{ forloop.revcounter }}</span>
            </span>
            <p class="date">{{ comment.created }}</p>
            <div class="well">
            <p style="margin-left:10px">{{comment.body}}</p></div>

        </div>
        {% empty %}
        <p>暂没有评论</p>
        {% endfor %}
    </div>
    <div style="margin-top:10px" class="well">
        <h4>
            <span class="glyphicon glyphicon-send"></span>欢迎拍砖
        </h4>

        <form action="." method="POST" class="form-horizontal" role="form">{% csrf_token %}
            <div class="form-group">
                <label for="inputcomment" class="col-sm-2 control-label">昵称</label>
                <div class="col-sm-10">
                    {{ comment_form.name }}
                </div>
            </div>
            <div class="form-group">
                <label for="inputcomment" class="col-sm-2 control-label">邮箱</label>
                <div class="col-sm-10">
                    {{ comment_form.email }}
                </div>
            </div>
            <div class="form-group">
                <label for="inputcomment" class="col-sm-2 control-label">评论</label>
                <div class="col-sm-10">
                    {{ comment_form.body }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <p><input type="submit" name="", value="发表评论" class="btn btn-primary" onclick="doreload()"></p>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript">
    function doreload(){
        parent.location.reload();
    }
</script>

templates/blog/article_post.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}新增博文{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top:10px">
            <div class="col-md-2 text-left">
                <span>标题:</span>

            </div>
            <div class="col-md-10 text-left">{{ article_post_form.title }}</div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-2 text-left">
                <span>类目:</span>
            </div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{ column.id }}">{{ column.column }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top:10px">
            <!--<div class="col-md-10 text-left">{{ article_post_form.body }}</div>-->
            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display:none;" id="id_body"></textarea>
            </div>
            <!--<div class="editormd" id="test-editormd">-->
                <!--<textarea class="editormd-markdown-textarea" name="test-editormd-markdown-doc"></textarea>-->
                <!--&lt;!&ndash; 第二个隐藏文本域，用来构造生成的HTML代码，方便表单POST提交，这里的name可以任意取，后台接受时以这个name键为准 &ndash;&gt;-->
                <!--<textarea class="editormd-html-textarea" name="text"></textarea>-->
            <!--</div>-->
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发 布" onclick="publish_article()">
        </div>
    </form>
</div>
<script type="text/javascript", src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript", src="{% static 'js/layer.js' %}"></script>

<script type="text/javascript">
    function publish_article(){
        var title = $("#id_title").val();
        var column_id = $("#which_column").val()
        var body = $("#id_body").val();
        $.ajax({
            url: "{% url 'blog:article_post' %}",
            type: "POST",
            data: {"title": title, "body": body, "column_id": column_id},
            success: function(e){
                if(e=="1"){
                    layer.msg("successful");
                    location.href="{% url 'blog:blog_title' %}";
                }
                else if(e=="2"){
                    layer.msg("Sorry.");
                }
                else{
                    layer.msg("类目名称必须填写，不能为空！");
                }
            }
        });
    }
</script>
<script type="text/javascript", src="{% static 'editor/editormd.js' %}"></script>
<script>
    $(function(){
        var editor = editormd("editormd", {
            width : "100%",
            height : "800",
            syncScrolling: "single",
            path : "{% static 'editor/lib/' %}"
        });
    });
</script>
{% endblock %}

templates/blog/article_redit.html
{% extends "base.html" %}

{% load staticfiles %}
{% block title %}编辑博文{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top:10px">
            <div class="col-md-2 text-left">
                <span>标题:</span>

            </div>
            <div class="col-md-10 text-left">{{ this_article_form.title }}</div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-2 text-left">
                <span>类目:</span>
            </div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                        {% if column.id == this_article_column.id %}
                            <option value="{{ column.id }}" selected="selected">{{ column.column }}</option>
                        {% else %}
                            <option value="{{ column.id }}">{{ column.column }}</option>
                        {% endif %}

                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top:10px">
            <!--<div class="col-md-10 text-left">{{ article_post_form.body }}</div>-->
            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display:none;" id="id_body">{{ article.body }}</textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发 布" onclick="article_redit()">
        </div>
    </form>
</div>
<script type="text/javascript", src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript", src="{% static 'editor/editormd.min.js' %}"></script>
<script type="text/javascript", src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript", src="{% static 'editor/editormd.js' %}"></script>
<script type="text/javascript">
    $(function(){
        var editor = editormd("editormd", {
            width : "100%",
            height : "800",
            //syncScrolling: "single",
            path : "{% static 'editor/lib/' %}"
        });
    });
</script>
<script type="text/javascript">
        function article_redit(){
        var title = $("#id_title").val();
        var column_id = $("#which_column").val()
        var body = $("#id_body").val();
        $.ajax({
            url: "{% url 'blog:article_redit' article.id %}",
            type: "POST",
            data: {"title": title, "body": body, "column_id": column_id},
            success: function(e){
                if(e=="1"){
                    layer.msg("successful");
                    location.href="{% url 'blog:blog_title' %}";
                }
                else if(e=="2"){
                    layer.msg("Sorry.");
                }
                else{
                    layer.msg("类目名称必须填写，不能为空！");
                }
            }
        });
    }
</script>
{% endblock %}

templates/blog/content.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" >
<div class="row text-left vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <div class="well">
            <p class="text-left">

                <span>
                    <a href="{% url 'blog:article_author' article.author.username %}">
                    <span style="margin-left:20px" class="glyphicon glyphicon-user"></span>
                        <span class="label label-default">{{ article.author.username }}</span>
                    </a>
                </span>
                <span>
                    <a href="/blog/article_column/{{ article.article_column_id }}">
                    <span style="margin-left:10px" class="glyphicon glyphicon-tag"></span>
                    <span class="label label-primary" >{{ article.column }}</span>
                    </a>
                </span>
                <span>
                    <a href="/blog/detail/{{ article.id }}/#article_comment">
                    <span style="margin-left:10px" class="glyphicon glyphicon-comment"></span>
                        评论({{ article.comments.count }})
                    </a>
                </span>
                <span>
                    <span style="margin-left:10px" class="glyphicon glyphicon-eye-open"></span>
                        浏览({{ views }})
                </span>
                <span style="margin-left:20px" class="glyphicon glyphicon-time">{{ article.created }}</span>
            </p>

            <div id="editormd-view">
                <textarea id="append-test" style="display:none;">{{ article.body }}
                </textarea>
            </div>
        </div>
        {% include "blog/article_comment.html" %}
    </div>
    <hr align="left" width="0" size="5" color="#808080">
    {% include "blog/article_hit.html" %}
    <!--{% include "adposition_right.html" %}-->
    <!--{% include "adposition_footer.html" %}-->
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'editor/lib/marked.min.js' %}"></script>
<script src="{% static 'editor/lib/prettify.min.js' %}"></script>
<script src="{% static 'editor/lib/raphael.min.js' %}"></script>
<script src="{% static 'editor/lib/underscore.min.js' %}"></script>
<script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
<script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
<script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
<script src="{% static 'editor/editormd.js' %}"></script>

<script type="text/javascript">
    $(function(){
        editormd.markdownToHTML("editormd-view", {
            htmlDecode : "style,script,iframe",
            emoji: true,
            taskList: true,
            tex: true,
            flowChart: true,
            sequenceDiagram: true,
        });
    });
</script>


{% endblock %}

templates/blog/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">
            <span style="margin-left:10px" class="glyphicon glyphicon-chevron-left"></span>
        </a>
        {% endif %}
        <span class="current" style="margin-left:10px">
            {{ page.number }}/ {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">
            <span style="margin-left:10px" class="glyphicon glyphicon-chevron-right"></span>
        </a>
        {% endif %}
    </span>
</div>

templates/blog/titles.html
{% extends "base.html" %}

{% load staticfiles %}
{% block title %}
Fly妃
{% endblock %}

{% block content %}

<div class="row">

    <hr align="left" width="0" size="5" color="#808080">

    <div class="col-xs-12 col-md-8">
        {% if blogs %}
            <ul>
                {% for blog in blogs %}
                <div class="well well-sm">
                    <h4><a href="/blog/detail/{{ blog.id }}">{{ blog.title }}</a></h4>
                    <div style="margin-top:10px">
                        <a href="{% url 'blog:article_author' blog.author.username %}">
                            <span style="margin-left:10px" class="glyphicon glyphicon-user"></span>
                            <span class="label label-default">{{ blog.author }}</span>
                        </a>
                        <a href="/blog/article_column/{{ blog.article_column_id }}">
                            <span style="margin-left:10px" class="glyphicon glyphicon-tag"></span>
                            <span class="label label-primary" >{{ blog.column }}</span>
                        </a>
                        <span>
                            <span style="margin-left:10px" class="glyphicon glyphicon-time"></span>
                            {{ blog.updated }}
                        </span>

                        {% if request.user.is_authenticated %}
                            {% ifequal request.user.username blog.author.username %}
                                <a name="redit-article" href="{% url 'blog:article_redit' blog.id %}">
                                    <span style="margin-left:25px" class="glyphicon glyphicon-edit"></span>编辑
                                </a>

                                <a name="delete" href="javascript:" onclick="del_article(this, {{ blog.id }})">
                                    <span style="margin-left:10px" class="glyphicon glyphicon-trash"></span>删除
                                </a>
                            {% endifequal %}
                        {% endif %}
                    </div>
                    <div class="well" style="margin-top:20px;height:300px; overflow-y :auto; verflow-x :hidden; white-space: wrap;">
                            {{ blog.body | safe }}
                    </div>

                    <div style="margin-top:5px">
                        <span>
                            <span style="margin-left:10px" class="glyphicon glyphicon-eye-open"></span>
                                浏览(
                            {% for view in views %}
                                {% ifequal blog.id view.id %}
                                    {{ view.views }}
                                {% endifequal %}
                            {% endfor %}
                            )
                            </a>
                        </span>
                        <span>
                            <span style="margin-left:10px" class="glyphicon glyphicon-comment"></span>
                                评论(
                           {{ blog.comments.count }}
                            )
                            </a>
                        </span>
                        <span>
                            <span style="margin-left:10px"><a class="btn btn-primary" href="/blog/detail/{{ blog.id }}" role="button">查看更多</a></span>
                        </span>
                    </div>
                </div>
                <hr align="left" width="0" size="5" color="#808080">
                {% empty %}

                {% endfor %}
            </ul>
            {% include "blog/paginator.html" %}
        {% else %}
            <p>
                博主太忙了，还没有博文
                <span style="margin-left:10px" class="glyphicon glyphicon-tint"></span>
            </p>
        {% endif %}
    </div>
    <hr align="left" width="0" size="5" color="#808080">
    <!--div class="row-xs-12 row-md-3"-->
    {% include "blog/article_hit.html" %}
    <!--{% include "adposition_right.html" %}-->
    <!--{% include "adposition_footer.html" %}-->
    </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function del_article(the, article_id){
        var article_name = $(the).parents("div").children("h4").text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            content: "<div class='text-center' style='margin-top:20px'> <p>是否确定删除 【" + article_name + "】</p></div>",
            btn: ['确定','取消'],
            yes: function(){
                $.ajax({
                    url: '{% url "blog:article_del" %}',
                    type: "POST",
                    data: {"article_id": article_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("删除成功");
                        }
                        else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }
</script>
<script type="text/javascript">
    $(function(){
        editormd.markdownToHTML("editormd-view", {
            htmlDecode : "style,script,iframe",
            emoji: true,
            taskList: true,
            tex: true,
            flowChart: true,
            sequenceDiagram: true,
        });
    });
</script
{% endblock %}