account/urls.py
'''
account urls
'''

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, {"template_name": "account/login.html"}, name="user_login"),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name="user_logout"),
    url(r'^$', auth_views.login, {"template_name": "account/login.html"}, name="user_login"),
]

blog/urls.py
'''
blog urls
'''

from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^detail/(?P<article_id>\d+)/$', views.blog_detail, name="blog_detail"),
    url(r'^article_column/(?P<column_id>\d+)/$', views.blog_article_column, name='article_column'),
    url(r'^article_author/(?P<username>[-\w]+)/$', views.blog_article_author, name='article_author'),
    url(r'^article_post/$', views.article_post, name='article_post'),
    url(r'^article_del/$', views.article_delete, name='article_del'),
    url(r'^article_redit/(?P<article_id>\d+)/$', views.article_redit, name='article_redit'),
    url(r'^$', views.blog_title, name="blog_title"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

urlpatterns = [
    url(r'^robots\.txt$', lambda r: HttpResponse('User-agent: *\nDisallow: /admin\nDisallow: /login\nDisallow: /account\nDisallow: /wx', content_type='text/plain')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include("account.urls", namespace="account", app_name="account")),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^account/', include("account.urls", namespace="account", app_name="account")),
    url(r'^wx/', include("wechat.urls", namespace="wechat", app_name="wechat")),
    url(r'^$', include("blog.urls", namespace="blog", app_name="blog")),
]

templates/adposition_footer.html
{% load staticfiles %}

<div class="col-xs-12 col-md-8" style="margin-top:30px;margin-right:30px;">
    <hr align="left" size="10" color="#808080">
    <img src="{% static 'images/test.jpg' %}">
</div>

templates/adposition_right.html
{% load staticfiles %}

<div class="col-xs-6 col-md-4">
    <hr align="left" size="10" color="#808080">
    <img width="200px" src="{% static 'images/test1.jpg' %}">
</div>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="baidu-site-verification" content="12KQ7gvu0x" />
    <meta name="viewport", content="width=device-width, initial-scale=1">

    <title>
        {% block title %}
        {% endblock %}
    </title>
    <style type="text/css">

      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }

      /* Set the fixed height of the footer here */
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }

      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          padding-left: 20px;
          padding-right: 20px;
        }
      }



      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

      #wrap > .container {
        padding-top: 60px;
      }
      .container .credit {
        margin: 20px 0;
      }

      code {
        font-size: 80%;
      }

    </style>
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <!--<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/layer.css' %}">
</head>

<body>


        {% include "header.html" %}
    <div id="wrap">
         <div class="container">
            {% block content %}
            {% endblock %}
         </div>

        <div id="push"></div>
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>
</body>
</html>

templates/footer.html
<div id="footer">
  <div class="container">
    <hr align="left" size="10" color="#808080">
    <p class="text-center">copy right www.flyfifi.cn 粤ICP备18032753号</a></p>
  </div>
</div>

templates/header.html
{% load staticfiles %}

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container" style='width: 90%;'>
		<div class="navbar-header" >
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li>
                        <a href="{% url 'blog:blog_title' %}">
                            <span style="margin-left:10px" class="glyphicon glyphicon-home"></span> HOME
                        </a>
                    </li>
				{% for column in columns %}
				<li>
					<a href="/blog/article_column/{{ column.id }}">{{ column.column }}</a>
				</li>
				{% empty %}
				{% endfor %}
			</ul>
			
			{% if request.user.is_authenticated %}
				<ul class="nav navbar-nav navbar-right" style="margin-right:10px">
					{% if user.is_authenticated %}
					<li><a href="#">{{ user.username }}</a> </li>
					<li><a href="{% url 'account:user_logout' %}">注销</a> </li>
					{% else %}
					<li>
						<a href="{% url 'account:user_login' %}">登录</a>
					</li>
					{% endif %}
					<li>
						<a name="add-article" href="{% url 'blog:article_post' %}">
							<span style="margin-left:10px" class="glyphicon glyphicon-plus"></span>新增博文
						</a>
					</li>
				</ul>
			{% endif %}
		</div>

    </div>
</nav>

<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>